# Yazi configuration file

[opener]
play = [
    { run = 'celluloid "$@"', orphan = true, for = "unix" },
]
edit = [
    { run = 'nvim "$@"', desc = "nvim", block = true, for = "unix" },
]
open = [
    { run = 'xdg-open "$1"', desc = "Open", for = "unix" },
]
reveal = [
    { run = 'xdg-open "$(dirname "$1")"', desc = "Reveal", for = "unix" },
    { run = '''exiftool "$1"; echo "Press enter to exit"; read _''', block = true, desc = "Show EXIF", for = "unix" },
]
pdf = [
    { run = 'zathura "$1"', desc = "Open with Zathura", for = "unix" },
]
markdown = [
    { run = 'glow "$1"', desc = "View with glow", for = "unix" },
]
extract = [
    { run = '7z x "$1"', block = true, desc = "Extract with 7z", for = "unix" },
]
view_archive = [
    { run = 'if [ -f "$1" ]; then case "$1" in *.tar) tar tf "$1" ;; *.zip) unzip -l "$1" ;; *.rar) unrar l "$1" ;; *.7z) 7z l "$1" ;; esac; echo "Press enter to exit"; read _; fi', block = true, desc = "View archive contents", for = "unix" },
]
ebook = [
    { run = 'ebook-viewer "$1"', desc = "Open with ebook-viewer", for = "unix" },
]

[open]
rules = [
    # Folder
    { name = "*/", use = ["open", "edit", "reveal"] },
    # Text
    { mime = "text/*", use = ["edit", "reveal"] },
    # Markdown
    { mime = "text/markdown", use = ["markdown", "edit", "reveal"] },
    # Image
    { mime = "image/*", use = ["open", "reveal"] },
    # Media
    { mime = "video/*", use = ["play", "reveal"] },
    { mime = "audio/*", use = ["play", "reveal"] },
    # Archive
    { mime = "application/{zip,rar,7z*,tar,gzip,xz,zstd,bzip*,lzma,compress,archive,cpio,arj,xar,ms-cab*}", use = ["extract", "view_archive", "reveal"] },
    # PDF
    { mime = "application/pdf", use = ["pdf", "reveal"] },
    # Ebooks
    { mime = "application/epub+zip", use = ["ebook", "reveal"] },
    # JSON
    { mime = "application/{json,ndjson}", use = ["edit", "reveal"] },
    # JavaScript
    { mime = "*/javascript", use = ["edit", "reveal"] },
    # Empty file
    { mime = "inode/empty", use = ["edit", "reveal"] },
    # Fallback
    { name = "*", use = ["open", "reveal"] },
]

[mgr]
show_hidden = true
