[config.wallpaper]
command = "awww"
arguments = ["img", "--transition-type", "center"]
set = false

[templates.waybar]
input_path = './templates/waybar.css'
output_path = '~/.config/waybar/colors.css'

[templates.gtk3]
input_path = './templates/gtk-colors.css'
output_path = '~/.config/gtk-3.0/colors.css'

[templates.gtk4]
input_path = './templates/gtk-colors.css'
output_path = '~/.config/gtk-4.0/colors.css'
